# Verilerin Sayısallaştırılması

### Bag of Words (BoW Yöntemiyle Kelimeleri Vektör Haline Getirme)

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer #bow modeli
import onIsleme

In [2]:
df=pd.read_csv("nlp-230518-121949.csv",index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [3]:
df["İşlenmiş Text"]=df["Text"].apply(onIsleme.preProcessing)
df["İşlenmiş Text"]=df["İşlenmiş Text"].apply(onIsleme.removeSpace)

In [4]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                       İşlenmiş Text  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [5]:
#boş liste kontrolü

df[df["İşlenmiş Text"].str[0].isnull()]

Text İşlenmiş Text
194  #hesaplamalısosyalbilimler #computationalsocia...            []
464  #investment #software #technology #tech #innov...            []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...            []

In [6]:
#boş satırları silme

df_index=df[df["İşlenmiş Text"].str[0].isnull()].index
df=df.drop(df_index)
df=df.reset_index()
del df["index"]

df[df["İşlenmiş Text"].str[0].isnull()]


Empty DataFrame
Columns: [Text, İşlenmiş Text]
Index: []

In [7]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                       İşlenmiş Text  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [8]:
df["İşlenmiş Text"]

0      [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
851                                   [dogal, dil, isle]
852       [ver, madencilik, doğal, dil, işle, uygulamas]
853    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: İşlenmiş Text, Length: 855, dtype: object

In [9]:
df["İşlenmiş Text 2"]=[' '.join(w for w in item) for item in df["İşlenmiş Text"]]
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                         İşlenmiş Text  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                       İşlenmiş Text 2  
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                     dogal dil isle  
852            ver madencilik doğal dil işle uygulamas  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [10]:
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(df["İşlenmiş Text 2"].to_list())
X

<855x4790 sparse matrix of type '<class 'numpy.int64'>'
	with 17076 stored elements in Compressed Sparse Row format>

In [11]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
df["BoW Yöntemiyle Temsil"]=X.toarray().tolist()
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                       İşlenmiş Text  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                     İşlenmiş Text 2  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                               BoW Yöntemiyle Temsil  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

### TF-IDF Yöntemi


BoW yönteminden daha sık kullanılır. Geleneksel makine öğrenmesi yöntemleriyle beraber daha sık kullanılır.

In [13]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer #tf-idf modeli
import onIsleme

In [14]:
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(df["İşlenmiş Text 2"].to_list())
X

<855x4790 sparse matrix of type '<class 'numpy.float64'>'
	with 17076 stored elements in Compressed Sparse Row format>

In [15]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
set(X.toarray()[0]) # X in 0 ıncı satırın içindeki unique değerler.

{0.0,
 0.03479110983131167,
 0.03654544101206711,
 0.12215193577015447,
 0.12765380745192684,
 0.1283253664065884,
 0.14813647411460532,
 0.15205170443790333,
 0.15346643018335335,
 0.1549440528967729,
 0.1655297853640538,
 0.17243193330717368,
 0.17509263596690622,
 0.18857071689305663,
 0.19813356749590907,
 0.2041092221131992,
 0.2116116484220595,
 0.22048848396825485,
 0.2211744990249119,
 0.23465257995106237,
 0.313614940472809}

In [17]:
df["TF-IDF Yöntemiyle Temsil"]=X.toarray().tolist()
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                         İşlenmiş Text  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                       İşlenmiş Text 2  \
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                 BoW Yöntemiyle Temsil  \
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                              TF-IDF Yöntemiyle Temsil  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

### Word2vec Yöntemi 

In [18]:
#! pip install gensim
from gensim.models import Word2Vec

In [19]:
model=Word2Vec(sentences=df["İşlenmiş Text"].tolist(),vector_size=100,window=5,min_count=1)
model.save("Word2Vec.model")

In [20]:
print(model)

Word2Vec(vocab=4801, vector_size=100, alpha=0.025)


In [21]:
words=list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 'yapay', 'zeka', 'il']

In [22]:
len(words)

4801

In [23]:
model.wv.get_vector("yapay") #vektörize değerleri

array([-0.02309695,  0.15199932,  0.04284688,  0.0008445 ,  0.04500235,
       -0.2804678 ,  0.07405935,  0.43994555, -0.09250105, -0.17956205,
        0.01013717, -0.24070425, -0.09246018,  0.18670084, -0.00687552,
       -0.1744503 ,  0.06775018, -0.1826186 ,  0.01304375, -0.33394137,
        0.16382946,  0.01922322,  0.17914717, -0.06580671,  0.00997323,
        0.02806973, -0.05353518, -0.02432702, -0.1910309 ,  0.00306172,
        0.25316504,  0.01243369,  0.04096157, -0.20396274, -0.07517383,
        0.16646059,  0.03469212, -0.1291742 , -0.08811934, -0.26969203,
       -0.03009688, -0.20296943, -0.06288297, -0.02488226,  0.14444104,
       -0.09072755, -0.15600263, -0.02270219,  0.04521295,  0.12636507,
        0.11382516, -0.21009764, -0.14514682, -0.08105924, -0.07570704,
        0.096658  ,  0.09189401, -0.03021407, -0.22203974,  0.04993106,
        0.03912785, -0.01674595,  0.05841536,  0.05042787, -0.21105573,
        0.2977428 ,  0.06093827,  0.10560796, -0.10465484,  0.27

In [24]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                       İşlenmiş Text  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                     İşlenmiş Text 2  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                               BoW Yöntemiyle Temsil  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                            TF-IDF Yöntemiyle Temsil  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [25]:
df["Word2Vec Yöntemiyle Temsil"]=df["İşlenmiş Text"].apply(onIsleme.word2vec)

In [26]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                       İşlenmiş Text  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                     İşlenmiş Text 2  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                               BoW Yöntemiyle Temsil  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                            TF-IDF Yöntemiyle Temsil  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                          Word2Vec Yöntemiyle Temsil  
0  [-0.007992156781256199, 0.06392935663461685, 0...  
1  [-0.005998990964144468, 0.050866685807704926, ...  
2  [-0.005420409142971039, 0.06177615374326706, 0...  
3  [-0.006924645975232124, 0.05438913777470589, 0...  
4  [-0.00922443438321352, 0.07560678571462631, 0....

### Son Değerlendirme

In [27]:
import onIsleme

In [28]:
df=pd.read_csv("nlp-230518-121949.csv",index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [29]:
df["İşlenmiş Text"]=df["Text"].apply(onIsleme.preProcessing)
df["İşlenmiş Text"]=df["İşlenmiş Text"].apply(onIsleme.removeSpace)

#boş liste kontrolü
df[df["İşlenmiş Text"].str[0].isnull()]


#boş satırları silme
df_index=df[df["İşlenmiş Text"].str[0].isnull()].index
df=df.drop(df_index)
df=df.reset_index()
del df["index"]



df["İşlenmiş Text 2"]=[' '.join(w for w in item) for item in df["İşlenmiş Text"]]
df.head()

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                         İşlenmiş Text  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                       İşlenmiş Text 2  
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                     dogal dil isle  
852            ver madencilik doğal dil işle uygulamas  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [36]:
df["BoW"]=onIsleme.bow(df["İşlenmiş Text 2"])
df["TF-IDF"]=onIsleme.tfIdf(df["İşlenmiş Text 2"])
df["Word2Vec"]=df["İşlenmiş Text"].apply(onIsleme.word2vec)

In [37]:
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                         İşlenmiş Text  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                       İşlenmiş Text 2  \
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                              Word2Vec  \
0    [-0.007992156781256199, 0.06392935663461685, 0...   
1    [-0.005998990964144468, 0.050866685807704926, ...   
2    [-0.005420409142971039, 0.06177615374326706, 0...   
3    [-0.006924645975232124, 0.05438913777470589, 0...   
4    [-0.00922443438321352, 0.07560678571462631, 0....   
..                                                 ...   
850  [-0.010684092529118061, 0.08058775216341019, 0...   
851  [-0.012253298424184322, 0.09506184607744217, 0...   
852  [-0.01440063863992691, 0.11564422398805618, 0....   
853  [-0.007586771156638861, 0.051518041640520096, ...   
854  [-0.004799028858542442, 0.04371662437915802, 0...   

                                                TF-IDF  \
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
..                                                 ...   
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                                   BoW  
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
..                                                 ...  
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, .